# Generated by Django 5.0.2 on 2024-03-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='out_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
